name: Test

concurrency:
  group: testing-${{ github.head_ref }}
  cancel-in-progress: true

on:
#  push:
#    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
         # ini-values: date.timezone=Europe/Paris
          
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: .package
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run linter suite
        run: PHP_CS_FIXER_IGNORE_ENV=1 .vendor/bin/php-cs-fixer fix --config=set/php-cs-fixer.php -v --dry-run

      - name: Run analyse suite
        run: composer run analyse

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Run test suite
        env:
            XDEBUG_MODE: coverage
        run: .vendor/bin/phpunit  --configuration=phpunit.xml